version: '3.3'

services:
  catalog:
    build: ./services/catalog
    container_name: catalog_service
    ports:
      - "8000:8000"
    env_file: ./services/catalog/.env
    depends_on:
      - db

  checkout:
    build: ./services/checkout
    container_name: checkout_service
    ports:
      - "8001:8001"
    env_file: ./services/checkout/.env
    depends_on:
      - db
      - catalog

  email:
    build: ./services/email
    container_name: email_service
    ports:
      - "8002:8002"
    env_file: ./services/email/.env
    depends_on:
      - db
      - checkout

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "80:80"
    depends_on:
      - catalog
      - checkout
    restart: always

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
